package org.fer.syncfiles.service;

import org.junit.Test;

import java.sql.SQLException;

/**
 * Created by fer on 28/11/14.
 */
public class DbPoolTest {
    @Test
    public void testPoolDb() throws SQLException {
//        DataSource ds = new DataSource();
//        ds.setDriverClassName("com.mysql.jdbc.Driver");
//        ds.setUrl("jdbc:mysql://localhost:3306/syncfiles");
//        ds.setUsername("sync");
//        ds.setPassword("sync");
//        ds.setInitialSize(5);
//        ds.setMaxActive(10);
//        ds.setMaxIdle(5);
//        ds.setMinIdle(2);
//
//        Connection con = ds.getConnection();
//        System.out.println("Super");
//        con.close();
//        System.out.println("Fin");

    }
}
